### ISSUE TITLE
CSS Modules error

### ISSUE THREAD

**Issue by Geuni620** [Geuni620/Traffic-Hub#20]
```CSS
/* @media (max-width: 768px) {
  .legend-group {
    margin: 0.5rem;
    width: calc(100% - 1rem);
    display: flex;
    align-items: center;
    justify-content: start;
    overflow-x: scroll;
    padding: 0.5rem;
  }

  .legend-group::-webkit-scrollbar {
    display: none;
  }
} */
```

모바일에서 범례의 사이즈를 수정하려고 하는데, 이 부분에서 에러가 발생함.
